{% set name = "pynetdicom" %}
{% set version = "2.1.1" %}
{% set sha256 = "d8d0cec1bc6fab893fa7f57ec7a49d71accefd8760c1a3b2726d8237b3a5715e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pydicom/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
    - poetry >=1.8
  run:
    - python >=3.10
    - pydicom >=2.4.0

test:
  requires:
    - poetry >=1.8
  imports:
    - pynetdicom

about:
  home: https://github.com/pydicom/pynetdicom
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: A Python implementation of the DICOM networking protocol
  description: |
    pynetdicom is a pure Python package that implements the
    DICOM networking protocol. Working with pydicom
    (https://github.com/pydicom/pydicom), it allows the easy creation of
    DICOM Service Class Users (SCUs) and Service Class Providers (SCPs)
    which can then be used to associate with other applications and transfer
    DICOM data.
  doc_url: https://pydicom.github.io/pynetdicom
  dev_url: https://github.com/pydicom/pynetdicom

extra:
  recipe-maintainers:
    - scaramallion
