{% set name = "pynetdicom" %}
{% set version = "2.0.2" %}
{% set sha256 = "470e48d98a1a6e596f75665ae5c47ca8046c7b7011784f02a67bd24235b03880" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pydicom/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pydicom >=2.0.0

test:
  requires:
    - setuptools
  imports:
    - pynetdicom

about:
  home: https://github.com/pydicom/pynetdicom
  license: MIT
  license_family: MIT
  license_file: LICENCE.txt
  summary: A Python implementation of the DICOM networking protocol
  description: |
    pynetdicom is a pure Python package that implements the
    DICOM networking protocol. Working with pydicom
    (https://github.com/pydicom/pydicom), it allows the easy creation of
    DICOM Service Class Users (SCUs) and Service Class Providers (SCPs)
    which can then be used to associate with other applications and transfer
    DICOM data.
  doc_url: https://pydicom.github.io/pynetdicom
  dev_url: https://github.com/pydicom/pynetdicom

extra:
  recipe-maintainers:
    - scaramallion
