{% set name = "pynetdicom" %}
{% set version = "1.5.4" %}
{% set sha256 = "8d5f84bda94679599e04aafbdb025f0d0d5f617e6e87be79865511a42ee7481f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pydicom/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pydicom 1.4.2

test:
  imports:
    - pynetdicom

about:
  home: https://github.com/pydicom/pynetdicom
  license: MIT
  license_family: MIT
  license_file: LICENCE.txt
  summary: A Python implementation of the DICOM networking protocol
  description: |
    pynetdicom is a pure Python package that implements the
    DICOM <http://dicom.nema.org> networking protocol. Working with pydicom
    <https://github.com/pydicom/pydicom>, it allows the easy creation of
    DICOM Service Class Users (SCUs) and Service Class Providers (SCPs)
    which can then be used to associate with other applications and transfer
    DICOM data.
  doc_url: https://pydicom.github.io/pynetdicom
  dev_url: https://github.com/pydicom/pynetdicom

extra:
  recipe-maintainers:
    - scaramallion
